// Auto-generated by Tools/build/generate_token.py

/* Token types */
#ifndef Py_INTERNAL_TOKEN_H
#define Py_INTERNAL_TOKEN_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

#define ENDMARKER       0
#define NAME            1
#define NAME_RAW        2
#define NUMBER          3
#define STRING          4
#define NEWLINE         5
#define INDENT          6
#define DEDENT          7
#define LPAR            8
#define RPAR            9
#define LSQB            10
#define RSQB            11
#define COLON           12
#define COMMA           13
#define SEMI            14
#define PLUS            15
#define MINUS           16
#define STAR            17
#define SLASH           18
#define VBAR            19
#define AMPER           20
#define LESS            21
#define GREATER         22
#define EQUAL           23
#define DOT             24
#define PERCENT         25
#define LBRACE          26
#define RBRACE          27
#define EQEQUAL         28
#define NOTEQUAL        29
#define JSXFRAGMENTOPEN 30
#define LESSEQUAL       31
#define GREATEREQUAL    32
#define TILDE           33
#define CIRCUMFLEX      34
#define LEFTSHIFT       35
#define RIGHTSHIFT      36
#define DOUBLESTAR      37
#define PLUSEQUAL       38
#define MINEQUAL        39
#define STAREQUAL       40
#define SLASHEQUAL      41
#define PERCENTEQUAL    42
#define AMPEREQUAL      43
#define VBAREQUAL       44
#define CIRCUMFLEXEQUAL 45
#define LEFTSHIFTEQUAL  46
#define RIGHTSHIFTEQUAL 47
#define DOUBLESTAREQUAL 48
#define DOUBLESLASH     49
#define DOUBLESLASHEQUAL 50
#define AT              51
#define ATEQUAL         52
#define RARROW          53
#define ELLIPSIS        54
#define COLONEQUAL      55
#define EXCLAMATION     56
#define OP              57
#define TYPE_IGNORE     58
#define TYPE_COMMENT    59
#define SOFT_KEYWORD    60
#define FSTRING_START   61
#define FSTRING_MIDDLE  62
#define FSTRING_END     63
#define COMMENT         64
#define NL              65
#define ERRORTOKEN      66
#define N_TOKENS        68
#define NT_OFFSET       256

/* Special definitions for cooperation with parser */

#define ISTERMINAL(x)           ((x) < NT_OFFSET)
#define ISNONTERMINAL(x)        ((x) >= NT_OFFSET)
#define ISEOF(x)                ((x) == ENDMARKER)
#define ISWHITESPACE(x)         ((x) == ENDMARKER || \
                                 (x) == NEWLINE   || \
                                 (x) == INDENT    || \
                                 (x) == DEDENT)
#define ISSTRINGLIT(x)          ((x) == STRING           || \
                                 (x) == FSTRING_MIDDLE)


// Export these 4 symbols for 'test_peg_generator'
PyAPI_DATA(const char * const) _PyParser_TokenNames[]; /* Token names */
PyAPI_FUNC(int) _PyToken_OneChar(int);
PyAPI_FUNC(int) _PyToken_TwoChars(int, int);
PyAPI_FUNC(int) _PyToken_ThreeChars(int, int, int);

#ifdef __cplusplus
}
#endif
#endif  // !Py_INTERNAL_TOKEN_H
